name: is2-notebooks
channels:
- conda-forge
dependencies:
- python=3.10
- xarray>=2023.01
- h5netcdf
- cmocean
- rioxarray>=0.3
- earthaccess>=0.5.1
- cfchecker
- matplotlib-base>=3.7
- cartopy>=0.18.0
- netcdf4>=1.5
- h5py>=3.2
- dask
- distributed
- hvplot
- datashader
- geoviews
- geopandas>=0.9
- geopandas
- jupyterlab>=3
- jupytext
- ipywidgets
- ipympl
- ipyleaflet
- jupyterlab-geojson
- jupyterlab-git
- jupyter-resource-usage
- jupyterlab-link-share
- jupyterlab-h5web
- gdal
- conda-lock
